### PR TITLE
Created POST API

### PR DESCRIPTION
**Pull request by Rits1272**
I have created REST API for saving confessions. The api takes two parameters: **name** and **message**. You can check the API in local setup using `curl` command:

` curl -H "content-type:application/json" -X POST -d '{"name":"NAME", "message": "CONFESSION"}' http://localhost:5000/api/post`

### CODE REVIEW

**Comment by Rits1272** [comment]
Solved issue #1. Please review @iharshit009.

**Comment by iharshit009** [comment]
Hey @Rits1272, Please check out [PEP 8](https://www.python.org/dev/peps/pep-0008/) Guide. Please follow the same while writing your code

**Comment by iharshit009** [comment]
LGTM
Hey @Rits1272, Please squash your commits.

**Comment by iharshit009** [comment]
That's the good one @Rits1272, Keep Learning:)

**Pull request merged**
